
CREATE TABLE AkariFis (
        objID           INT4      CONSTRAINT akarifis_pkey PRIMARY KEY,
        objName         VARCHAR(14)  UNIQUE NOT NULL, -- fixed length
        ra              FLOAT8    NOT NULL,
        dec             FLOAT8    NOT NULL,
        posErrMj        FLOAT4    NOT NULL,
        posErrMi        FLOAT4    NOT NULL,
        posErrPA        FLOAT4    NOT NULL,
        flux_65         FLOAT4,
        flux_90         FLOAT4,
        flux_140        FLOAT4,
        flux_160        FLOAT4,
        fErr_65         FLOAT4,
        fErr_90         FLOAT4,
        fErr_140        FLOAT4,
        fErr_160        FLOAT4,
        fQual_65        INT2      NOT NULL,
        fQual_90        INT2      NOT NULL,
        fQual_140       INT2      NOT NULL,
        fQual_160       INT2      NOT NULL,
        flags_65        INT2,
        flags_90        INT2,
        flags_140       INT2,
        flags_160       INT2,
        nScanC_65       INT2      NOT NULL,
        nScanC_90       INT2      NOT NULL,
        nScanC_140      INT2      NOT NULL,
        nScanC_160      INT2      NOT NULL,
        nScanP_65       INT2      NOT NULL,
        nScanP_90       INT2      NOT NULL,
        nScanP_140      INT2      NOT NULL,
        nScanP_160      INT2      NOT NULL,
        mConf_65        INT2,
        mConf_90        INT2,
        mConf_140       INT2,
        mConf_160       INT2,
        nDens           INT2      NOT NULL,
        cx              FLOAT8    NOT NULL,
        cy              FLOAT8    NOT NULL,
        cz              FLOAT8    NOT NULL
);


