
# If you want to create composite index for "ra" and "dec" columns, set "ra:dec,dec:ra".
INDICES = w1_mpro,w2_mpro,w3_mpro,w4_mpro

all::
	sh ../mk.sh update $(INDICES)

clean::
	sh ../mk.sh clean $(INDICES)

