#define _TABLE_INFO_SRC__C "ppmxl_table_info._c"
#define _RADIALSEARCH_FNC_NAME _ppmxlgetsqlforradialsearch
#define _BOXSEARCHSIMPLE_FNC_NAME _ppmxlgetsqlforboxsearchsimple
#define _BOXSEARCHDIV_FNC_NAME _ppmxlgetsqlforboxsearchdiv
#define _RECTANGULARSEARCH_FNC_NAME _ppmxlgetsqlforrectangularsearch
#include "huge_search_fnc_template._c"
