#define _TABLE_INFO_SRC__C "ucac3_table_info._c"
#define _RADIALSEARCH_FNC_NAME _ucac3getsqlforradialsearch
#define _BOXSEARCHSIMPLE_FNC_NAME _ucac3getsqlforboxsearchsimple
#define _BOXSEARCHDIV_FNC_NAME _ucac3getsqlforboxsearchdiv
#define _RECTANGULARSEARCH_FNC_NAME _ucac3getsqlforrectangularsearch
#include "huge_search_fnc_template._c"
